### ISSUE TITLE
Missing chroot.sh

### ISSUE THREAD

**Issue by kaloyan-raev** [fread-ink/fread-userland#1]
I am going through the instruction, but `sudo ./setup_chroot_env.sh` fails with:
```
cp: cannot stat ‘/vagrant/chroot.sh’: No such file or directory
```
Indeed, I don't see any `chroot.sh` file in the github repo.

**Comment by Juul** [comment]
Ok I'll have a look tonight.

**Comment by Juul** [comment]
Found the missing chroot!

**Comment by kaloyan-raev** [comment]
Thanks!
