### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [fread-ink/fread-userland#3]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

I see your many of your other repos mention GPLv3.  Are these GPL-3.0-only or GPL-3.0-or-later?

**Comment by Juul** [comment]
Thanks. Fixed. They are GPLv3 only.
